name = "hadirga"
license = "MIT License"
description = "A bootstrap4 Hugo theme for notes."
homepage = "https://github.com/hadirga/hugo-hadirga"
tags = ["bootstrap", "blog", "font awesome", "hadirga", "docs"]
features = ["responsive", "blog"]
min_version = 0.25

[author]
  name = "Hadir Garcia-Castro"
  homepage = "https://hadir.ga"

[based on]
  name = "Chris Albon"
  homepage = "https://chrisalbon.com"

  name = "Digitalcraftsman"
  homepage = "https://github.com/digitalcraftsman"

  name = "Alan Orth"
  homepage = "https://englishbulgaria.net"

[original]
  author = "mdo"
  homepage = "https://v4-alpha.getbootstrap.com/examples/blog/"

  name = "Martin Donath"
  homepage = "http://struct.cc/"
  repo = "https://github.com/squidfunk/mkdocs-material"
